"""
AI Script Analyzer

Parses Python scripts generated by AI coding assistants using Tree-Sitter to extract:
- Import statements and their usage
- Class instantiations and method calls  
- Function calls with parameters
- Attribute access patterns
- Variable type tracking
"""

import tree_sitter
import tree_sitter_python
from tree_sitter import Language, Parser

import logging
from pathlib import Path
from typing import Dict, List, Set, Any, Optional, Tuple
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class ImportInfo:
    """Information about an import statement"""
    module: str
    name: str
    alias: Optional[str] = None
    is_from_import: bool = False
    line_number: int = 0


@dataclass
class MethodCall:
    """Information about a method call"""
    object_name: str
    method_name: str
    args: List[str]
    kwargs: Dict[str, str]
    line_number: int
    object_type: Optional[str] = None  # Inferred class type


@dataclass
class AttributeAccess:
    """Information about attribute access"""
    object_name: str
    attribute_name: str
    line_number: int
    object_type: Optional[str] = None  # Inferred class type


@dataclass
class FunctionCall:
    """Information about a function call"""
    function_name: str
    args: List[str]
    kwargs: Dict[str, str]
    line_number: int
    full_name: Optional[str] = None  # Module.function_name


@dataclass
class ClassInstantiation:
    """Information about class instantiation"""
    variable_name: str
    class_name: str
    args: List[str]
    kwargs: Dict[str, str]
    line_number: int
    full_class_name: Optional[str] = None  # Module.ClassName


@dataclass
class AnalysisResult:
    """Complete analysis results for a Python script"""
    file_path: str
    imports: List[ImportInfo] = field(default_factory=list)
    class_instantiations: List[ClassInstantiation] = field(default_factory=list)
    method_calls: List[MethodCall] = field(default_factory=list)
    attribute_accesses: List[AttributeAccess] = field(default_factory=list)
    function_calls: List[FunctionCall] = field(default_factory=list)
    variable_types: Dict[str, str] = field(default_factory=dict)  # variable_name -> class_type
    errors: List[str] = field(default_factory=list)


class AIScriptAnalyzer:
    """Analyzes AI-generated Python scripts for validation against knowledge graph using Tree-sitter"""
    
    def __init__(self):
        self.import_map: Dict[str, str] = {}  # alias -> actual_module_name
        self.variable_types: Dict[str, str] = {}  # variable_name -> class_type
        self.context_manager_vars: Dict[str, Tuple[int, int, str]] = {}  # var_name -> (start_line, end_line, type)
        
        self.language = Language(tree_sitter_python.language())
        self.parser = Parser(self.language)

    def analyze_script(self, script_path: str) -> AnalysisResult:
        """Analyze a Python script and extract all relevant information"""
        try:
            with open(script_path, 'r', encoding='utf-8') as f:
                content = f.read()
            self.content_bytes = bytes(content, "utf8")
            tree = self.parser.parse(self.content_bytes)
            result = AnalysisResult(file_path=script_path)
            
            # Reset state for new analysis
            self.import_map.clear()
            self.variable_types.clear()
            self.context_manager_vars.clear()
            
            # Track processed nodes to avoid duplicates
            self.processed_calls = set()
            self.method_call_attributes = set()
            
            def walk_nodes(node):
                yield node
                for child in node.children:
                    yield from walk_nodes(child)
                    
            # First pass: collect imports and build import map
            for node in walk_nodes(tree.root_node):
                if node.type in ('import_statement', 'import_from_statement'):
                    self._extract_imports(node, result)
                    
            # Second pass: analyze usage patterns
            for node in walk_nodes(tree.root_node):
                self._analyze_node(node, result)
                
            # Set inferred types on method calls and attribute accesses
            self._infer_object_types(result)
            
            result.variable_types = self.variable_types.copy()
            return result
            
        except Exception as e:
            error_msg = f"Failed to analyze script {script_path}: {str(e)}"
            logger.error(error_msg)
            result = AnalysisResult(file_path=script_path)
            result.errors.append(error_msg)
            return result

    def _get_text(self, node) -> str:
        """Helper to extract text from a tree-sitter node"""
        if not node: return ""
        return self.content_bytes[node.start_byte:node.end_byte].decode("utf8")

    def _extract_imports(self, node, result: AnalysisResult):
        """Extract import information and build import mapping"""
        line_num = node.start_point[0] + 1
        
        if node.type == 'import_statement':
            for child in node.children:
                if child.type == 'dotted_name':
                    import_name = self._get_text(child)
                    result.imports.append(ImportInfo(
                        module=import_name, name=import_name, alias=None,
                        is_from_import=False, line_number=line_num
                    ))
                    self.import_map[import_name] = import_name
                elif child.type == 'aliased_import':
                    dotted_node = child.child_by_field_name('name') or child.children[0]
                    alias_node = child.child_by_field_name('alias') or child.children[2]
                    import_name = self._get_text(dotted_node)
                    alias_name = self._get_text(alias_node)
                    result.imports.append(ImportInfo(
                        module=import_name, name=import_name, alias=alias_name,
                        is_from_import=False, line_number=line_num
                    ))
                    self.import_map[alias_name] = import_name
                    
        elif node.type == 'import_from_statement':
            module_node = node.child_by_field_name('module_name')
            module = self._get_text(module_node) if module_node else ""
            
            for child in node.children:
                if child.type == 'dotted_name':
                    import_name = self._get_text(child)
                    result.imports.append(ImportInfo(
                        module=module, name=import_name, alias=None,
                        is_from_import=True, line_number=line_num
                    ))
                    full_name = f"{module}.{import_name}" if module else import_name
                    self.import_map[import_name] = full_name
                elif child.type == 'aliased_import':
                    dotted_node = child.child_by_field_name('name') or child.children[0]
                    alias_node = child.child_by_field_name('alias') or child.children[2]
                    import_name = self._get_text(dotted_node)
                    alias_name = self._get_text(alias_node)
                    result.imports.append(ImportInfo(
                        module=module, name=import_name, alias=alias_name,
                        is_from_import=True, line_number=line_num
                    ))
                    full_name = f"{module}.{import_name}" if module else import_name
                    self.import_map[alias_name] = full_name

    def _analyze_node(self, node, result: AnalysisResult):
        """Analyze individual AST nodes for usage patterns"""
        line_num = node.start_point[0] + 1
        
        # Assignments (class instantiations and method call results)
        if node.type == 'assignment':
            left = node.child_by_field_name('left')
            right = node.child_by_field_name('right')
            
            if left and left.type == 'identifier' and right and right.type == 'call':
                func_node = right.child_by_field_name('function')
                if func_node and func_node.type == 'identifier':
                    # Direct function/class call assignment (e.g., agent = SuperAgent())
                    self._extract_class_instantiation(node, left, right, result)
                    self.processed_calls.add(right.id)
                elif func_node and func_node.type == 'attribute':
                    # Method call assignment (e.g., result = agent.run())
                    var_name = self._get_text(left)
                    # Track for type inference later
                    self.variable_types[var_name] = "method_result"
                    self._extract_method_call(right, result)
                    self.processed_calls.add(right.id)

        # AsyncWith / With statements (context managers)
        elif node.type == 'with_statement':
            is_async = any(c.type == 'async' for c in node.children)
            clause = node.child_by_field_name('clause')
            if not clause:
                for child in node.children:
                    if child.type == 'with_clause':
                        clause = child
                        break
            
            if clause:
                for item in clause.children:
                    if item.type == 'with_item':
                        self._handle_with_item(item, is_async, node, result)

        # Method calls and function calls (not an assignment)
        elif node.type == 'call':
            if node.id in self.processed_calls:
                return
            func_node = node.child_by_field_name('function')
            if func_node:
                if func_node.type == 'attribute':
                    self._extract_method_call(node, result)
                    self.method_call_attributes.add(func_node.id)
                elif func_node.type == 'identifier':
                    func_name = self._get_text(func_node)
                    full_name = self._resolve_full_name(func_name)
                    # Check if this is likely a class instantiation
                    if self._is_likely_class_instantiation(func_name, full_name):
                        self._extract_nested_class_instantiation(node, result)
                    else:
                        self._extract_function_call(node, result)

        # Attribute access (not in call context)
        elif node.type == 'attribute':
            if node.id in self.method_call_attributes:
                return
            
            parent = node.parent
            if parent and parent.type in ('assignment', 'module', 'call'):
                pass
                
            self._extract_attribute_access(node, result)

    def _handle_with_item(self, item, is_async, stmt_node, result):
        """Handle 'with' or 'async with' context managers"""
        as_pattern = None
        call_node = None
        for child in item.children:
            if child.type == 'as_pattern':
                as_pattern = child
                break
        
        if as_pattern:
            for child in as_pattern.children:
                if child.type == 'call':
                    call_node = child
            
            target_node = as_pattern.child_by_field_name('target') or as_pattern.children[-1]
            var_name = self._get_text(target_node)
            
            if call_node and call_node.child_by_field_name('function') and call_node.child_by_field_name('function').type == 'attribute':
                self._extract_method_call(call_node, result)
                self.processed_calls.add(call_node.id)
                
                func_node = call_node.child_by_field_name('function')
                obj_node = func_node.child_by_field_name('object')
                attr_node = func_node.child_by_field_name('attribute')
                
                obj_name = self._get_text(obj_node)
                method_name = self._get_text(attr_node)
                
                start_line = stmt_node.start_point[0] + 1
                end_line = stmt_node.end_point[0] + 1
                
                # Specialized tracking for run_stream yield vars
                if is_async and obj_name in self.variable_types and 'pydantic_ai' in str(self.variable_types[obj_name]) and method_name == 'run_stream':
                    self.context_manager_vars[var_name] = (start_line, end_line, "pydantic_ai.StreamedRunResult")
                else:
                    self.variable_types[var_name] = "context_manager_result"

    def _extract_args(self, call_node) -> Tuple[List[str], Dict[str, str]]:
        """Extract arguments and keyword arguments from a call node"""
        args = []
        kwargs = {}
        arg_list = call_node.child_by_field_name('arguments')
        if not arg_list:
            return args, kwargs
            
        for arg in arg_list.children:
            if arg.type == 'keyword_argument':
                name_node = arg.child_by_field_name('name')
                val_node = arg.child_by_field_name('value')
                if name_node and val_node:
                    kwargs[self._get_text(name_node)] = self._get_text(val_node)
            elif arg.type not in ('(', ')', ','):
                args.append(self._get_text(arg))
        return args, kwargs

    def _extract_class_instantiation(self, assign_node, target_node, call_node, result: AnalysisResult):
        """Extract class instantiation from assignment"""
        var_name = self._get_text(target_node)
        func_node = call_node.child_by_field_name('function')
        class_name = self._get_text(func_node)
        
        args, kwargs = self._extract_args(call_node)
        full_class_name = self._resolve_full_name(class_name)
        
        instantiation = ClassInstantiation(
            variable_name=var_name,
            class_name=class_name,
            args=args, kwargs=kwargs,
            line_number=call_node.start_point[0] + 1,
            full_class_name=full_class_name
        )
        result.class_instantiations.append(instantiation)
        # Store for subsequent method call mapping
        self.variable_types[var_name] = full_class_name or class_name

    def _extract_method_call(self, call_node, result: AnalysisResult):
        """Extract information from a method call against a class instance"""
        func_node = call_node.child_by_field_name('function')
        if not func_node or func_node.type != 'attribute': return
        
        obj_node = func_node.child_by_field_name('object')
        attr_node = func_node.child_by_field_name('attribute')
        
        if not obj_node or not attr_node: return
        
        obj_name = self._get_text(obj_node)
        method_name = self._get_text(attr_node)
        
        args, kwargs = self._extract_args(call_node)
        
        method_call = MethodCall(
            object_name=obj_name,
            method_name=method_name,
            args=args, kwargs=kwargs,
            line_number=call_node.start_point[0] + 1,
            object_type=self.variable_types.get(obj_name)
        )
        result.method_calls.append(method_call)

    def _extract_function_call(self, call_node, result: AnalysisResult):
        """Extract standard function call details"""
        func_node = call_node.child_by_field_name('function')
        func_name = self._get_text(func_node)
        args, kwargs = self._extract_args(call_node)
        full_func_name = self._resolve_full_name(func_name)
        
        function_call = FunctionCall(
            function_name=func_name,
            args=args, kwargs=kwargs,
            line_number=call_node.start_point[0] + 1,
            full_name=full_func_name
        )
        result.function_calls.append(function_call)

    def _extract_nested_class_instantiation(self, call_node, result: AnalysisResult):
        """Extract a class instantiated anonymously (e.g. inside a return or a list)"""
        func_node = call_node.child_by_field_name('function')
        class_name = self._get_text(func_node)
        args, kwargs = self._extract_args(call_node)
        full_class_name = self._resolve_full_name(class_name)
        var_name = f"<{class_name.lower()}_instance>"
        
        instantiation = ClassInstantiation(
            variable_name=var_name, class_name=class_name,
            args=args, kwargs=kwargs, line_number=call_node.start_point[0] + 1,
            full_class_name=full_class_name
        )
        result.class_instantiations.append(instantiation)

    def _extract_attribute_access(self, attr_node, result: AnalysisResult):
        """Extract dot-based attribute access (e.g., config.timeout)"""
        obj_node = attr_node.child_by_field_name('object')
        field_node = attr_node.child_by_field_name('attribute')
        if not obj_node or not field_node: return
        
        obj_name = self._get_text(obj_node)
        attr_name = self._get_text(field_node)
        
        attribute_access = AttributeAccess(
            object_name=obj_name, attribute_name=attr_name,
            line_number=attr_node.start_point[0] + 1,
            object_type=self.variable_types.get(obj_name)
        )
        result.attribute_accesses.append(attribute_access)

    def _infer_object_types(self, result: AnalysisResult):
        """Resolve deferred attribute types based on contextual yield bounds"""
        for method_call in result.method_calls:
            if not method_call.object_type:
                obj_type = self._get_context_aware_type(method_call.object_name, method_call.line_number)
                method_call.object_type = obj_type or self.variable_types.get(method_call.object_name)
        
        for attr_access in result.attribute_accesses:
            if not attr_access.object_type:
                obj_type = self._get_context_aware_type(attr_access.object_name, attr_access.line_number)
                attr_access.object_type = obj_type or self.variable_types.get(attr_access.object_name)

    def _get_context_aware_type(self, var_name: str, line_number: int) -> Optional[str]:
        """Verify variables scoped by active context managers"""
        if var_name in self.context_manager_vars:
            start_line, end_line, var_type = self.context_manager_vars[var_name]
            if start_line <= line_number <= end_line:
                return var_type
        return None

    def _resolve_full_name(self, name: str) -> Optional[str]:
        """Convert referenced class identifier into fully qualified python import name"""
        if name in self.import_map:
            return self.import_map[name]
        parts = name.split('.')
        if len(parts) > 1 and parts[0] in self.import_map:
            base_module = self.import_map[parts[0]]
            return f"{base_module}.{'.'.join(parts[1:])}"
        return None

    def _is_likely_class_instantiation(self, func_name: str, full_name: Optional[str]) -> bool:
        """Heuristics to determine if a call evaluates to a Class definition"""
        if func_name and func_name[0].isupper(): return True
        if full_name:
            class_patterns = ['Model', 'Provider', 'Client', 'Agent', 'Manager', 'Handler', 'Builder', 'Factory', 'Service', 'Controller', 'Processor']
            return any(pattern in full_name for pattern in class_patterns)
        return False


def analyze_ai_script(script_path: str) -> AnalysisResult:
    """Convenience function to analyze a single AI-generated script"""
    analyzer = AIScriptAnalyzer()
    return analyzer.analyze_script(script_path)


if __name__ == "__main__":
    # Example usage
    import sys
    
    if len(sys.argv) != 2:
        print("Usage: python ai_script_analyzer.py <script_path>")
        sys.exit(1)
    
    script_path = sys.argv[1]
    result = analyze_ai_script(script_path)
    
    print(f"Analysis Results for: {result.file_path}")
    print(f"Imports: {len(result.imports)}")
    print(f"Class Instantiations: {len(result.class_instantiations)}")
    print(f"Method Calls: {len(result.method_calls)}")
    print(f"Function Calls: {len(result.function_calls)}")
    print(f"Attribute Accesses: {len(result.attribute_accesses)}")
    
    if result.errors:
        print(f"Errors: {result.errors}")